export interface IPaciente {
    codatencion: string;
    codpaciente: string;
    nombrepaciente: string;
    titular: string;
    fechainicio: string;
    fechafin : string;
    cama: string;
    nombresexo: string;
    codplan: string;
    porcentajeplan: number;
    edad: number;
    direccion: string;
    telefono: string;
    nombreprovincia: string;
    nombredistrito: string;
    poliza : string;
    planpoliza: string;
    npoliza: string;
    codaseguradora : string;
    nombreaseguradora: string;
    nombrecontratante: string;
    codcia: string;
    codmedico: string;
    nombremedico: string;
    observacionesasegurado: string;
    observacionespaciente: string;
    observacionatencion: string;
    fechainiciovigencia: Date;
    fechafinvigencia: Date;
    numerodiasatencion: number;
    nombretarifa: string;
    nombreparentesco: string;
    coaseguro: number;
    deducible: number;
    descuento: number;
    nombreconcepto: string;
    nombremoneda: string;
    activo: number;
    pagacoaseguro: string;
    familiar: string;
    traslado: string;
    exclusiones: string;
    codatenciondestino: string;
    idegctipoatencionmae: number;
    descripcionpaquete: string;
}